name: Deploy Laravel to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          coverage: none

      - name: Update Composer
        run: composer self-update

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest --verbose
        
      - name: Create .env file
        run: |
          cp .env.example .env
          sed -i 's/APP_ENV=.*/APP_ENV=production/' .env
          sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' .env
          sed -i 's/APP_URL=.*/APP_URL=https:\/\/thecoral.darwinrg.me/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_coral/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=coral/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env
        
      - name: Generate application key
        run: php artisan key:generate --force
        
      - name: Directory permissions
        run: chmod -R 755 storage bootstrap/cache
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -v -H thecoral.darwinrg.me >> ~/.ssh/known_hosts || (sleep 5 && ssh-keyscan -v -H thecoral.darwinrg.me >> ~/.ssh/known_hosts)
        shell: /usr/bin/bash -e {0}
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1
          SSH_AUTH_SOCK: /tmp/ssh-dpLCnYpy4XAr/agent.2809
          SSH_AGENT_PID: 2810
        
      - name: Deploy to production
        run: |
          rsync -avz --delete --exclude-from='.deployignore' ./ coral@thecoral.darwinrg.me:/var/www/laravel-coral/
          
      - name: Run post-deployment tasks
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: coral.darwinrg.me
          username: coral
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/laravel-coral
            php artisan migrate --force
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache