name: Deploy Laravel to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          coverage: none
          
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        
      - name: Create .env file
        run: |
          cp .env.example .env
          sed -i 's/APP_ENV=.*/APP_ENV=production/' .env
          sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' .env
          sed -i 's/APP_URL=.*/APP_URL=https:\/\/coral.darwinrg.me/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_coral/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=coral/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env
        
      - name: Generate application key
        run: php artisan key:generate --force
        
      - name: Directory permissions
        run: chmod -R 755 storage bootstrap/cache
        
      # Deploy using appleboy/scp-action
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: coral
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/laravel-coral-temp"
          strip_components: 0
          overwrite: true
          
      # Run post-deployment commands
      - name: Run post-deployment tasks
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: coral
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Move files from temp directory to production
            rsync -avz --delete --exclude '.git' --exclude 'storage/app/*' --exclude 'storage/logs/*' --exclude 'storage/framework/sessions/*' /var/www/laravel-coral-temp/ /var/www/laravel-coral/
            
            # Set base permissions
            sudo chown -R coral:www-data /var/www/laravel-coral
            
            # Create required storage directories if they don't exist
            mkdir -p /var/www/laravel-coral/storage/framework/{sessions,views,cache}
            mkdir -p /var/www/laravel-coral/storage/logs
            
            # Run Laravel commands
            cd /var/www/laravel-coral
          
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:clear
            php artisan view:cache
            php artisan migrate --force
            php artisan storage:link
            
            # Clean up temp directory
            rm -rf /var/www/laravel-coral-temp
            
            # THE CRITICAL FIX - Set 777 permissions AFTER everything else is done
            sudo chmod -R 777 /var/www/laravel-coral/storage
            sudo chmod -R 777 /var/www/laravel-coral/bootstrap/cache